import React from 'react';
import './gardensetup.scss';
import { translations } from '../translations';

function GardenSetup({ language }) {
  return (
    <div className="garden-setup">
      <h1>{translations[language].gardenSetupTitle}</h1>
      <h2>{translations[language].stepByStepGuide}</h2>
      <ol>
        <li>
          <h3>{translations[language].gardenStep1Title}</h3>
          <p>{translations[language].gardenStep1Desc}</p>
          <ul>
            <li>{translations[language].gardenStep1Point1}</li>
            <li>{translations[language].gardenStep1Point2}</li>
            <li>{translations[language].gardenStep1Point3}</li>
            <li>{translations[language].gardenStep1Point4}</li>
          </ul>
        </li>
        <li>
          <h3>{translations[language].gardenStep2Title}</h3>
          <p>{translations[language].gardenStep2Desc}</p>
          <ul>
            <li>{translations[language].gardenStep2Point1}</li>
            <li>{translations[language].gardenStep2Point2}</li>
            <li>{translations[language].gardenStep2Point3}</li>
            <li>{translations[language].gardenStep2Point4}</li>
          </ul>
        </li>
        <li>
          <h3>{translations[language].gardenStep3Title}</h3>
          <p>{translations[language].gardenStep3Desc}</p>
          <ul>
            <li>{translations[language].gardenStep3Point1}</li>
            <li>{translations[language].gardenStep3Point2}</li>
            <li>{translations[language].gardenStep3Point3}</li>
            <li>{translations[language].gardenStep3Point4}</li>
          </ul>
        </li>
        <li>
          <h3>{translations[language].gardenStep4Title}</h3>
          <p>{translations[language].gardenStep4Desc}</p>
          <ul>
            <li>{translations[language].gardenStep4Point1}</li>
            <li>{translations[language].gardenStep4Point2}</li>
            <li>{translations[language].gardenStep4Point3}</li>
            <li>{translations[language].gardenStep4Point4}</li>
          </ul>
        </li>
        <li>
          <h3>{translations[language].gardenStep5Title}</h3>
          <p>{translations[language].gardenStep5Desc}</p>
          <ul>
            <li>{translations[language].gardenStep5Point1}</li>
            <li>{translations[language].gardenStep5Point2}</li>
            <li>{translations[language].gardenStep5Point3}</li>
            <li>{translations[language].gardenStep5Point4}</li>
          </ul>
        </li>
      </ol>
      <h2>{translations[language].snowRemoval}</h2>
      <ol>
        <li>
          <h3>{translations[language].snowStep1Title}</h3>
          <p>{translations[language].snowStep1Desc}</p>
          <ul>
            <li>{translations[language].snowStep1Point1}</li>
            <li>{translations[language].snowStep1Point2}</li>
            <li>{translations[language].snowStep1Point3}</li>
            <li>{translations[language].snowStep1Point4}</li>
          </ul>
        </li>
        <li>
          <h3>{translations[language].snowStep2Title}</h3>
          <p>{translations[language].snowStep2Desc}</p>
          <ul>
            <li>{translations[language].snowStep2Point1}</li>
            <li>{translations[language].snowStep2Point2}</li>
            <li>{translations[language].snowStep2Point3}</li>
            <li>{translations[language].snowStep2Point4}</li>
          </ul>
        </li>
        <li>
          <h3>{translations[language].snowStep3Title}</h3>
          <p>{translations[language].snowStep3Desc}</p>
          <ul>
            <li>{translations[language].snowStep3Point1}</li>
            <li>{translations[language].snowStep3Point2}</li>
            <li>{translations[language].snowStep3Point3}</li>
          </ul>
        </li>
      </ol>
      <h2>{translations[language].patioMaintenance}</h2>
      <ol>
        <li>
          <h3>{translations[language].patioStep1Title}</h3>
          <p>{translations[language].patioStep1Desc}</p>
          <ul>
            <li>{translations[language].patioStep1Point1}</li>
            <li>{translations[language].patioStep1Point2}</li>
            <li>{translations[language].patioStep1Point3}</li>
            <li>{translations[language].patioStep1Point4}</li>
          </ul>
        </li>
        <li>
          <h3>{translations[language].patioStep2Title}</h3>
          <p>{translations[language].patioStep2Desc}</p>
          <ul>
            <li>{translations[language].patioStep2Point1}</li>
            <li>{translations[language].patioStep2Point2}</li>
            <li>{translations[language].patioStep2Point3}</li>
            <li>{translations[language].patioStep2Point4}</li>
          </ul>
        </li>
        <li>
          <h3>{translations[language].patioStep3Title}</h3>
          <p>{translations[language].patioStep3Desc}</p>
          <ul>
            <li>{translations[language].patioStep3Point1}</li>
            <li>{translations[language].patioStep3Point2}</li>
            <li>{translations[language].patioStep3Point3}</li>
            <li>{translations[language].patioStep3Point4}</li>
          </ul>
        </li>
      </ol>
    </div>
  );
}

export default GardenSetup;
